### ISSUE TITLE
Love 11.0 color scheme change

### ISSUE THREAD

**Issue by jamesalbert** [wilhantian/catui#3] opened 2018-04-16 01:34 UTC
All colors specified are in the range 0..255, but as of Love 11.0 colors are in a 0..1 range. Here are all the occurrences I was able to find with `grep 'color = {' -rinI .`, there *might* be more:
```
     1	./doc/modules/catui.Control.UIButton.html:369:         color = {r, g, b, a}
     2	./doc/modules/catui.Control.UIButton.html:390:         color = {r, g, b, a}
     3	./doc/modules/catui.Control.UIButton.html:411:         color = {r, g, b, a}
     4	./doc/modules/catui.Control.UIButton.html:432:         color = {r, g, b, a}
     5	./doc/modules/catui.Control.UIButton.html:476:         color = {r, g, b, a}
     6	./catui/UITheme.lua:35:theme.button.upColor = {57, 69, 82, 255}
     7	./catui/UITheme.lua:36:theme.button.downColor = {30, 35, 41, 255}
     8	./catui/UITheme.lua:37:theme.button.hoverColor = {71, 87, 103, 255}
     9	./catui/UITheme.lua:38:theme.button.disableColor = {48, 57, 66, 255}
    10	./catui/UITheme.lua:39:theme.button.strokeColor = {25, 30, 35, 255}
    11	./catui/UITheme.lua:43:theme.button.fontColor = {255, 255, 255, 255}
    12	./catui/UITheme.lua:47:theme.scrollBar.upColor = {84, 108, 119, 255}
    13	./catui/UITheme.lua:48:theme.scrollBar.hoverColor = {112, 158, 184, 255}
    14	./catui/UITheme.lua:49:theme.scrollBar.downColor = {84, 108, 119, 255}
    15	./catui/UITheme.lua:50:theme.scrollBar.backgroundColor = {47, 59, 69, 255}
    16	./catui/UITheme.lua:52:theme.content.backgroundColor = {31, 36, 43, 255}
    17	./catui/UITheme.lua:55:theme.checkBox.upColor = {255, 255, 255, 255}
    18	./catui/UITheme.lua:56:theme.checkBox.downColor = {0, 150, 224, 255}
    19	./catui/UITheme.lua:57:theme.checkBox.hoverColor = {0, 150, 224, 255}
    20	./catui/UITheme.lua:58:theme.checkBox.disableColor = {84, 108, 119, 255}
    21	./catui/UITheme.lua:61:theme.progressBar.color = {57, 104, 149, 255}
    22	./catui/UITheme.lua:62:theme.progressBar.backgroundColor = {47, 59, 69, 255}
    23	./catui/UITheme.lua:64:theme.editText.backgroundColor = {255, 255, 255, 255}
    24	./catui/UITheme.lua:65:theme.editText.focusStrokeColor = {57, 104, 149, 255}
    25	./catui/UITheme.lua:66:theme.editText.unfocusStrokeColor = {41, 50, 59, 255}
    26	./catui/UITheme.lua:67:theme.editText.cursorColor = {82, 139, 255, 255}
    27	./catui/Control/UILabel.lua:39:    color = {0, 0, 0, 255},
    28	./catui/Control/UIButton.lua:219:-- @tab color color = {r, g, b, a}
    29	./catui/Control/UIButton.lua:227:-- @tab color color = {r, g, b, a}
    30	./catui/Control/UIButton.lua:235:-- @tab color color = {r, g, b, a}
    31	./catui/Control/UIButton.lua:243:-- @tab color color = {r, g, b, a}
    32	./catui/Control/UIButton.lua:259:-- @tab color color = {r, g, b, a}
```

**Comment by wilhantian** [comment] 2018-04-18 08:03
thanks for your advice.
I don't have the energy to maintain this project now.
You can submit RP.
feel free to contact.

**Comment by dodoqumy** [comment] 2018-04-18 08:25
fighting

**Comment by To-mos** [comment] 2018-04-30 15:27
I made the changes on one of my projects but don't have a repo available to merge with, so here are the new colors.

```
local theme = {}

theme.button = {}
theme.button.width            = 80
theme.button.height           = 36
theme.button.upColor          = {0.224, 0.271, 0.322, 1.0}--{57, 69, 82, 255}
theme.button.downColor        = {0.180, 0.220, 0.259, 1.0}--{46, 56, 66, 255}
theme.button.hoverColor       = {0.251, 0.302, 0.357, 1.0}--{64, 77, 91, 255}
theme.button.disableColor     = {0.318, 0.318, 0.318, 1.0}--{81, 81, 81, 255}
theme.button.strokeColor      = {0.180, 0.220, 0.259, 1.0}--{46, 56, 66, 255}
theme.button.stroke           = 1
theme.button.font             = "font/visat.ttf"
theme.button.fontSize         = 16
theme.button.fontColor        = {1.0, 1.0, 1.0, 1.0}--{255, 255, 255, 255}
theme.button.iconDir          = "left"
theme.button.iconAndTextSpace = 8

theme.slider = {}
theme.slider.width        = 100
theme.slider.height       = 15
theme.slider.upColor      = {0.224, 0.271, 0.322, 1.0}--{57, 69, 82, 255}
theme.slider.downColor    = {0.180, 0.220, 0.259, 1.0}--{46, 56, 66, 255}
theme.slider.hoverColor   = {0.251, 0.302, 0.357, 1.0}--{64, 77, 91, 255}
theme.slider.disableColor = {0.318, 0.318, 0.318, 1.0}--{81, 81, 81, 255}
theme.slider.barColor     = {0.329, 0.424, 0.466, 1.0}--{84, 108, 119, 255}
theme.slider.barThickness = 4
theme.slider.font         = "font/visat.ttf"
theme.slider.fontSize     = 16
theme.slider.fontColor    = {1.0, 1.0, 1.0, 1.0}--{255, 255, 255, 255}

theme.scrollBar = {}
theme.scrollBar.upColor         = {0.224, 0.271, 0.322, 1.0}--{57, 69, 82, 255}
theme.scrollBar.hoverColor      = {0.251, 0.302, 0.357, 1.0}--{64, 77, 91, 255}
theme.scrollBar.downColor       = {0.180, 0.220, 0.259, 1.0}--{46, 56, 66, 255}
theme.scrollBar.backgroundColor = {0.141, 0.176, 0.208, 1.0}--{36, 45, 53, 255}

theme.content = {}
theme.content.backgroundColor = {0.122, 0.141, 0.169, 1.0}--{31, 36, 43, 255}
theme.content.resizeColor     = {0.224, 0.271, 0.322, 1.0}--{57, 69, 82, 255}
theme.content.barSize         = 14

theme.checkBox = {}
theme.checkBox.upColor      = {1.0, 1.0, 1.0, 1.0}--{255, 255, 255, 255}
theme.checkBox.downColor    = {0.0, 0.588, 0.957, 1.0}--{0, 150, 224, 255}
theme.checkBox.hoverColor   = {0.0, 0.588, 0.957, 1.0}--{0, 150, 224, 255}
theme.checkBox.disableColor = {0.329, 0.424, 0.466, 1.0}--{84, 108, 119, 255}
theme.checkBox.size         = 16

theme.progressBar = {}
theme.progressBar.width           = 100
theme.progressBar.height          = 10
theme.progressBar.color           = {0.224, 0.408, 0.584, 1.0}--{57, 104, 149, 255}
theme.progressBar.backgroundColor = {0.184, 0.231, 0.271, 1.0}--{47, 59, 69, 255}

theme.node = {}
theme.node.width        = 20
theme.node.height       = 20
theme.node.upColor      = {0.224, 0.271, 0.322, 1.0}--{57, 69, 82, 255}
theme.node.downColor    = {0.118, 0.137, 0.161, 1.0}--{30, 35, 41, 255}
theme.node.hoverColor   = {0.278, 0.341, 0.404, 1.0}--{71, 87, 103, 255}
theme.node.disableColor = {0.188, 0.224, 0.259, 1.0}--{48, 57, 0.259, 255}

theme.editText = {}
theme.editText.backgroundColor    = {1.0, 1.0, 1.0, 1.0}--{255, 255, 255, 255}
theme.editText.focusStrokeColor   = {0.224, 0.408, 0.584, 1.0}--{57, 104, 149, 255}
theme.editText.unfocusStrokeColor = {0.161, 0.196, 0.231, 1.0}--{41, 50, 59, 255}
theme.editText.cursorColor        = {0.322, 0.545, 1.0, 1.0}--{82, 139, 255, 255}
theme.editText.stroke             = 1

return theme
```

**Comment by wilhantian** [comment] 2018-06-11 10:29
Duplicate of #5

**Closed by wilhantian** 2018-06-11 10:29 UTC

**Comment by wilhantian** [comment] 2018-06-11 10:31
#5 thinks @Scorbie
